internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace="api")),
    path('api-auth-token/', obtain_auth_token, name="auth-token"),
    path('', include('order.urls', namespace="order")),
    path('', include('user.urls', namespace="user")),
    path('', include('product.urls', namespace="products")),

]

order/urls.py
from django.urls import path
from django.views.generic import DeleteView

from order.views import OrderListView, OrderCreateView, OrderDetailView, OrderUpdateView, \
    OrderDeleteView

app_name = "order"
urlpatterns = [
    path("order/", OrderListView.as_view(), name="order-list"),
    path("<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path("create/", OrderCreateView.as_view(), name="order-create"),
    path("<int:pk>/update/", OrderUpdateView.as_view(), name="order-update"),
    path("<int:pk>/delete/", OrderDeleteView.as_view(), name="order-delete"),
]

product/urls.py
from django.urls import path

from product.views import ProductListView, ReviewCreateView,  ProductDetailView, AddToCartView,\
    PurchaseView

app_name = "product"
urlpatterns = [
    path("", ProductListView.as_view(), name="product_list"),
    path("products/<slug:slug>/", ProductDetailView.as_view(), name="product_detail"),
    path("review/", ReviewCreateView.as_view(), name="review"),
    path("add-to-cart/<slug:slug>/", AddToCartView.as_view(), name="add-to-cart"),
    path("purchase/", PurchaseView.as_view(), name="purchase"),
]

user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from user.views import UserSignInView, UserSignUpView,  UserProfileView
app_name = "user"
urlpatterns = [
    path("sign-up/", UserSignUpView.as_view(), name="sign-up"),
    path("sign-in/", UserSignInView.as_view(), name="sign-in"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", UserProfileView.as_view(), name="profile")
]

internet_shop/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
   <title>{% block doctitle %}Internet shop{% endblock %}</title>
</head>
<body>
<header>{% include "navbar.html" %}</header>
{% block content%}

{%endblock content%}

</body>
</html>

internet_shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><a href="{% url "product:product_list" %}" class="nav-link">Products</a></li>
      </ul>
      <div class="d-flex">
      <li class="nav-link">Hello, {{ request.user }} !</li>
        {% if request.user.is_authenticated %}
          {% if request.user.is_staff %}
            <a href="{% url "admin:index" %}" class="btn">Admin</a>
            {% else %}
            <a href="{% url "order:order-create" %}" class="btn">Buy</a>
            <a href="{% url "order:order-list" %}" class="btn">Orders</a>
          {% endif %}
            <a href="{% url "user:profile" %}" class="btn">Profile</a>
          <a href="{% url "user:logout" %}" class="btn">Logout</a>
        {% else %}
          <a href="{% url "user:sign-in" %}" class="btn">Login</a>
          <a href="{% url "user:sign-up" %}" class="btn">Register</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>