internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace="api")),
    path('api-auth-token/', obtain_auth_token, name="auth-token"),
    path('', include('order.urls', namespace="order")),
    path('', include('user.urls', namespace="user")),
    path('', include('product.urls', namespace="products")),

]

order/urls.py
from django.urls import path
from django.views.generic import DeleteView

from order.views import OrderListView, OrderCreateView, OrderDetailView, OrderUpdateView, \
    OrderDeleteView

app_name = "order"
urlpatterns = [
    path("order/", OrderListView.as_view(), name="order-list"),
    path("<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path("create/", OrderCreateView.as_view(), name="order-create"),
    path("<int:pk>/update/", OrderUpdateView.as_view(), name="order-update"),
    path("<int:pk>/delete/", OrderDeleteView.as_view(), name="order-delete"),
]

user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from user.views import UserSignInView, UserSignUpView,  UserProfileView
app_name = "user"
urlpatterns = [
    path("sign-up/", UserSignUpView.as_view(), name="sign-up"),
    path("sign-in/", UserSignInView.as_view(), name="sign-in"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", UserProfileView.as_view(), name="profile")
]

order/models.py
from django.db import models
from django.urls import reverse_lazy

from product.models import Product


class Order(models.Model):
    class Meta:
        db_table = "order"
        verbose_name = "order"
        verbose_name_plural = "orders"

    id = models.BigAutoField(primary_key=True)

    CREATED = 1
    CANCELED = 2
    CONFIRMED = 3
    COMPLETED = 4
    REJECTED = 5

    ORDER_STATUSES = [
        [CREATED, "Created"],
        [CANCELED, "Canceled"],
        [CONFIRMED, "Confirmed"],
        [COMPLETED, "Completed"],
        [REJECTED, "Rejected"],
    ]
    status = models.IntegerField(choices=ORDER_STATUSES, default=1)
    created_date = models.DateField(auto_created=True, auto_now=True)
    updated_date = models.DateField(auto_now=True)
    address = models.CharField(max_length=255)
    is_deleted = models.BooleanField(default=False)
    product = models.ForeignKey(
        "product.Product",
        on_delete=models.SET_NULL,
        null=True,
        related_name="+",
    )
    quantity = models.PositiveIntegerField()
    customer = models.ForeignKey(
        "auth.User", on_delete=models.CASCADE, related_name="+"
    )

    def __repr__(self):
        return f"Order ('{self.id}')"

    def __str__(self):
        return f"{self.id}|-product: {self.product}|-status: {self.status}|-address: {self.address}" \
               f"|-quantity:  {self.quantity}"

    def get_absolute_url(self):
        return reverse_lazy("order:order_detail", kwargs={"pk": self.id})

order/forms.py
from django import forms

from product.models import Product
from order.models import Order
from django.contrib.auth.models import User


class OrderForms(forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"

api/views/order.py
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from order.models import Order
from order.serializers import OrderSerializer


class OrderListAPIView(ListCreateAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer


class OrderDetailAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    lookup_url_kwarg = "id"
    lookup_field = "id"

order/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from order.models import Order


class OrderListView(ListView):
    http_method_names = ["head", "options", "get"]
    model = Order
    template_name = "order/list.html"

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()

        return queryset.filter(customer=self.request.user, is_deleted=False)


class OrderDetailView(DetailView):
    http_method_names = ["head", "options", "get"]
    model = Order

    def get(self, *args, **kwargs):
        order = self.get_object()
        if order.customer != self.request.user:
            redirect_url = reverse_lazy("order:order-list")
            return HttpResponseRedirect(redirect_url)

        return super(OrderDetailView, self).get(*args, **kwargs)


class OrderCreateView(CreateView):
    model = Order
    fields = ["product", "quantity", "address"]

    def form_valid(self, form):
        form.instance.customer = self.request.user
        return super(OrderCreateView, self).form_valid(form)


class OrderUpdateView(LoginRequiredMixin, UpdateView):
    model = Order
    fields = ["quantity", "address"]
    template_name = "order/order_form.html"

    def get(self, *args, **kwargs):
        order = self.get_object()
        if order.customer != self.request.user:
            redirect_url = reverse_lazy("order:order-list")
            return HttpResponseRedirect(redirect_url)

        return super(OrderUpdateView, self).get(*args, **kwargs)

    def post(self, *args, **kwargs):
        order = self.get_object()
        if order.status < Order.CONFIRMED:
            return super(OrderUpdateView, self).post(*args, **kwargs)

        redirect_url = order.get_absolute_url()
        return HttpResponseRedirect(redirect_url)


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("order:list")
    template_name = "order/order_confirm_detail.html"

    def get(self, *args, **kwargs):
        order = self.get_object()

        if order.customer != self.request.user:
            redirect_url = reverse_lazy("order:order-list")
            return HttpResponseRedirect(redirect_url)

        return super(OrderDeleteView, self).get(*args, **kwargs)

    def post(self, *args, **kwargs):
        order = self.get_object()

        if order.status < Order.CONFIRMED:
            order.is_deleted = True
            order.save()
            redirect_url = reverse_lazy("order:order-list")

        else:
            redirect_url = order.get_absolute_url()

        return HttpResponseRedirect(redirect_url)

internet_shop/templates/order/list.html
{% extends "base.html" %}
{% block doctitle %}Orders |{{ block.super }}{% endblock %}
{% block content %}

<ul>
    <h1>Orders</h1>
    {% for order in order_list %}
        <li>{{ order }}</li>
{% endfor %}
</ul>
    <a href="{% url "order:order-create" %}">Create Order</a>

{% endblock %}

internet_shop/templates/order/order_confirm_detail.html
{% extends "base.html" %}
{% block doctitle %}Cancel Order | {{ block.super }}{% endblock %}
{% block content %}
  <form class="row" method="post">
    {% csrf_token %}
    <div class="text-body">Are you sure you want to cancel this order?</div>
    <div>
      <input type="submit" class="btn btn-danger" value="Yes, Cancel this">
      <a href="{% url "order:order-detail" pk=object.pk %}" class="btn btn-secondary">No, Leave it</a>
    </div>
  </form>
{% endblock %}

internet_shop/templates/order/order_detail.html
{% extends "base.html" %}
{% block doctitle %}Order | {{ block.super }}{% endblock %}
{% block content %}
  <div class="row">
    <div class="col">
      <h5>Order Details</h5>
    </div>
  </div>
  <div class="row">
    <div class="col">
      Order status: {{ object.status }}
    </div>
    <div class="col">
      Product: {{ object.product }}
    </div>
    <div class="col">
      Quantity: {{ object.quantity }}
    </div>
  </div>
  <div class="row">
    <div class="col">
      <p>Delivery Address:</p>
      <p>{{ object.address|linebreaks }}</p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <a href="{% url "order:order-update" pk=object.pk %}" class="btn btn-primary">Update Order</a>
      <a href="{% url "order:order-delete" pk=object.pk %}" class="btn btn-danger">Cancel Order</a>
    </div>
  </div>
{% endblock %}

internet_shop/templates/order/order_form.html
{% extends "base.html" %}
{% block doctitle %}Order Form | {{ block.super }}{% endblock %}
{% block content %}
  <form class="row" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary col-1" value="Create">
    <a href="{% url "order:order-list" %}" class="col-1 btn btn-secondary">Cancel</a>
  </form>
{% endblock %}