internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace="api")),
    path('api-auth-token/', obtain_auth_token, name="auth-token"),
    path('', include('order.urls', namespace="order")),
    path('', include('user.urls', namespace="user")),
    path('', include('product.urls', namespace="products")),

]

order/urls.py
from django.urls import path
from django.views.generic import DeleteView

from order.views import OrderListView, OrderCreateView, OrderDetailView, OrderUpdateView, \
    OrderDeleteView

app_name = "order"
urlpatterns = [
    path("order/", OrderListView.as_view(), name="order-list"),
    path("<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path("create/", OrderCreateView.as_view(), name="order-create"),
    path("<int:pk>/update/", OrderUpdateView.as_view(), name="order-update"),
    path("<int:pk>/delete/", OrderDeleteView.as_view(), name="order-delete"),
]

product/urls.py
from django.urls import path

from product.views import ProductListView, ReviewCreateView,  ProductDetailView, AddToCartView,\
    PurchaseView

app_name = "product"
urlpatterns = [
    path("", ProductListView.as_view(), name="product_list"),
    path("products/<slug:slug>/", ProductDetailView.as_view(), name="product_detail"),
    path("review/", ReviewCreateView.as_view(), name="review"),
    path("add-to-cart/<slug:slug>/", AddToCartView.as_view(), name="add-to-cart"),
    path("purchase/", PurchaseView.as_view(), name="purchase"),
]

user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from user.views import UserSignInView, UserSignUpView,  UserProfileView
app_name = "user"
urlpatterns = [
    path("sign-up/", UserSignUpView.as_view(), name="sign-up"),
    path("sign-in/", UserSignInView.as_view(), name="sign-in"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", UserProfileView.as_view(), name="profile")
]

product/models.py
from django.contrib import auth
from django.urls import reverse_lazy
from django.utils.translation import gettext as _

from django.db import models
from django.template.defaultfilters import slugify
from django.views.generic import RedirectView

import product
from product.validators import positive_validator
from django.core.validators import MaxValueValidator


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.CharField(max_length=255)

    def __repr__(self):
        return f"<{self.__class__.__name__} pk={self.pk} ('{self}')>"

    def __str__(self):
        return self.category

    @property
    def name(self):
        return self.category


class Product(models.Model):
    id = models.AutoField(primary_key=True, null=False, blank=True)
    product = models.CharField(max_length=255, verbose_name=_("a product title"),
                               help_text=_("255 characters or fever"))
    amount = models.IntegerField(validators=[MaxValueValidator(1)], help_text=_("a positive "
                                                                                "integer"))
    product_description = models.CharField(max_length=1000, null=True)
    image = models.ImageField(upload_to='static/media/', null=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True,
                                 db_column='category')
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[positive_validator])
    slug = models.SlugField(max_length=255, help_text=_("letters, hyphens, numbers and"
                                                        " underscores"))

    def __repr__(self):
        return f"<{self.__class__.__name__} pk={self.pk} ('{self}')>"

    def __str__(self):
        return self.product

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.product)
        if self.amount < 0:
            self.amount = 0

        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):

        return reverse_lazy("product:product_detail", kwargs={"slug": self.slug})

    @property
    def name(self):
        return self.product


class Review(models.Model):
    RATE_CHOICES = [
        [1, 1], [2, 2], [3, 3], [4, 4], [5, 5]
    ]

    id = models.BigAutoField(primary_key=True)
    rate = models.PositiveSmallIntegerField(
        choices=RATE_CHOICES, default=5, verbose_name="product rate"
    )
    review = models.TextField(blank=True)

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="reviews"
    )

    class Meta:
        verbose_name = "product review"
        verbose_name_plural = "product reviews"

    def __repr__(self):
        return f"<Review ({self.id}) rate={self.rate}>"

    def __str__(self):
        return str(self.rate)


class Cart(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    def get_total(self):
        total = 0.0
        for cart_item in self.cart_items:
            total + cart_item.get.total()

        return total


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField(default=1)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="cart_items")

    def get_total(self):
        return Product.price * self.quantity


class Purchase(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)

product/forms.py
from django import forms
from product.models import Product
from django.core.exceptions import ValidationError


class ReviewForms(forms.Form):
    review = forms.CharField(label="Product review")
    rate = forms.IntegerField(label="Product rate", max_value=5, min_value=1)
    product = forms.ModelChoiceField(required=False, queryset=Product.objects.all())

    def clean_review(self):
        review = self.cleaned_data.get("review")
        if not review:
            raise ValidationError("review text required")
        else:
            return review

    def clean_rate(self):
        rate = self.cleaned_data.get("rate")
        if rate < 1 or rate > 5:
            raise ValidationError("rate should be between 1 or 5")

    def clean(self):
        super().clean()

api/views/product.py
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from django.views.generic import ListView
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from product.models import Product
from product.serializers import ProductSerializer


class ProductListAPIView(ListCreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class ProductDetailAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    lookup_url_kwarg = "slug"
    lookup_field = "slug"

product/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, RedirectView
from rest_framework.response import Response
from rest_framework import status

from product.forms import ReviewForms
from product.models import Product, Category, Review, Cart, CartItem
from rest_framework.views import APIView

from rest_framework.decorators import api_view

from product.serializers import ProductSerializer


class ProductListView(ListView):
    model = Product
    http_method_names = ["get", "head", "options", "trace"]
    template_name = "product/product.html"

    def get_queryset(self):
        queryset = super(ProductListView, self).get_queryset()
        category_id = self.request.GET.get("category_id")
        if category_id is not None:
            queryset.filter(category_id=category_id)
        return queryset.exclude(id=0)

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        context["categories"] = Category.objects.all()
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = "product/product_detail.html"
    slug_field = "slug"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context["form"] = ReviewForms()
        return context


class ReviewCreateView(CreateView):
    template_name = "product_detail.html"
    http_method_names = ["post", "head", "options", ]
    model = Review
    form_class = ReviewForms

    def get_success_url(self):
        return reverse_lazy("products:product_detail", kwargs={"slug": self.kwargs.get("slug")})

    def form_valid(self, form):
        slug = self.kwargs.get("slug")
        response = HttpResponseRedirect(self.get_success_url())

        if self.request.session.get(slug) is not None:
            return response

        try:
            product = Product.objects.get(slug=slug)
            form.instance.product = product

            super(ReviewCreateView, self).form_valid(form)

            max_age = 300
            self.request.session.set_expiry(max_age)

            self.request.session[slug] = slug
            return response

        except Product.DoesNotExist:
            return Http404()


class AddToCartView(RedirectView):
    def get(self, *args, **kwargs):
        cart = self.request.session.get("cart", {})
        product_slug = self.kwargs.get("slug")
        if product_slug in cart:
            cart[product_slug] += 1
        else:
            cart[product_slug] = 1
        self.request.session["cart"] = cart
        redirect_url = self.request.headers.get('referer') or reverse_lazy(
            "product:product_list")
        return HttpResponseRedirect(redirect_url)


class PurchaseView(View):
    def get(self, request, *args, **kwargs):
        session_cart = request.session.get('cart')
        if session_cart is None:
            redirect_url = self.request.headers.get('referer') or reverse_lazy(
                "product:product_list")
            return HttpResponseRedirect(redirect_url)
        user = self.request.user
        cart = Cart.objects.get_or_create(user=user, is_active=True)
        for product_slug in session_cart:
            product = Product.objects.get(slug=product_slug)
            quantity = session_cart[product_slug]
            cart_item = CartItem(product=product, quantity=quantity, cart=cart)
            cart_item.save()
            self.request.session["cart"] = {}
        redirect_url = self.request.headers.get('referer') or reverse_lazy(
            "product:product_list")
        return HttpResponseRedirect(redirect_url)

internet_shop/templates/product/_review_form.html
<form class="row row-cols-md-auto" action="{% url "product:review" %}" method="post">
  {% csrf_token %}
  <div class="col-11">
    {{ form.as_p}}
  </div>
  <div class="col">
    <button type="submit" class="btn btn-primary">Post</button>
  </div>
</form>

internet_shop/templates/product/product.html
{% extends "base.html" %}
{% block doctitle %} Product list |  {{ block.super }}{% endblock %}
{% block content %}
    <form  method="post">
{% csrf_token %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for product in product_list %}
<div class="col">
<div class="card h-100">
                   <img src="{{ product.image}}" alt="
{{ product.image }}" width="300" height="300">
            <div class="card-body">
                <p class="card-context">Price:  {{ product.price }} $</p>
            <p class="card-text">{{ product.product_description|truncatewords:"300" }}</p>
               <ul> <a href="{% url "product:product_detail" slug=product.slug %}">
                   <div class="card-footer"><a href=
                           "{% url "product:add-to-cart" slug=product.slug %}">Add
                    to cart</a></div>
                {{product.product}}</a></ul>
                <div class="card-footer"><a href={% url "order:order-create" %}>Buy </a></div>
               </div>
               </div>
            </div>
        {% endfor %}
    </div>
</form>
{% endblock %}

internet_shop/templates/product/product_cart.html
<div class="col">
  <div class="card h-100">
    <img src="{{ product.image }}" class="card-img-top" alt="{{ product.slug }}">
    <div class="card-body">
      <h5 class="card-title">{{ product }}</h5>
      <span>{{ product.rate|default_if_none:"unrated" }}</span>
      <p class="text-end">{{ product.price|floatformat:"2" }} UAH</p>
      <p class="card-text">{{ product.description|truncatewords:"10" }}</p>
      {% if product.quantity == 0 %}
        <small class="text-muted">Not available</small>
      {% endif %}
    </div>
    <div class="card-footer">
      <small class="d-flex text-muted">{{ product.category }}</small>
      <div class="text-end">
        Reviews: <span class="badge  bg-secondary">{{ product.reviews.count }}</span>
      </div>
      <div class="d-flex">
        <a href="{% url "detail" slug=product.slug %}" class="btn btn-outline-primary">View Details</a>
      </div>
    </div>
  </div>
</div>

internet_shop/templates/product/product_detail.html
{% extends "product/product.html" %}
{% block content %}
  <h5 class="h5">{{ object.product }}</h5>
  <div class="row">
    <div class="col text-end">Price:  {{ object.price|floatformat:"2" }} USD</div>
      <img src="{{ object.image }}" alt="image">
  </div>
  <div class="row">
    <div class="text-body">Description:  {{ object.description }}</div>
  </div>
  <hr>
  <div class="row">
    <ul class="list-group">
      {% for review in object.reviews.all %}
        <li class="list-group-item d-flex justify-content-between align-items-start mb-2">
          <div class="ms-2 me-auto">
            <div class="fw-bold">{{ review.rate }}</div>
            {{ review.review }}
          </div>
        </li>
      {% endfor %}
    </ul>
  </div>
  {% include "product/_review_form.html" %}
{% endblock %}

internet_shop/templates/product/review.html
{% extends "base.html" %}
{% block title %}Product detail|  {{ block.super }}{% endblock %}
{% block content %}
    <form action="{% url "products:review" %}" method="post">
{% csrf_token %}
    {{ form.as_p }}



</form>
{% endblock %}